### ISSUE TITLE
Create Wiki

### ISSUE THREAD

**Issue by rodrigosiqueira** [Kuniri/kuniri#13]
You should explain:
1 - What is Kuniri and its objectives.
2 - How to contribute and Development cycle.
3 - Architecture explanation.
4 - Code pattern.
5 - Contributors.

**Comment by fabraz** [comment]
Take a look on http://aosabook.org/en/index.html.

**Comment by rodrigosiqueira** [comment]
https://github.com/rodrigosiqueira/kuniri/wiki
