### ISSUE TITLE
Ruby Inheritance Tests

### ISSUE THREAD

**Issue by JohnnysRibeiro** [Kuniri/kuniri#135]
Currently, kuniri doesn't tests if the name of the inheritance is correct, only if the name of the class is correct when it has a inheritance

**Comment by rodrigosiqueira** [comment]
@JohnnysRibeiro, can you work on this issue this week? If you cannot finish it, please let' me know.
You can assign this issue to me. ;)

**Comment by JohnnysRibeiro** [comment]
@rodrigosiqueira this issue is already closed. sorry for not noticing you before. The last context in class_ruby_spec.rb tests this.
