### ISSUE TITLE
Create test to verify the integrity of xml

### ISSUE THREAD

**Issue by rodrigosiqueira** [Kuniri/kuniri#147]
@lucasmoura found problems with the output integrity. We need to create a set of strong tests, for check the final output of kuniri.
@lucasmoura can you focus in this issue?

**Comment by lucasmoura** [comment]
No problem, I will start as soon as possible.

**Comment by rodrigosiqueira** [comment]
@lucasmoura can you work on this issue this week? If you can't, let'me know. I can finish it ;)

**Comment by rodrigosiqueira** [comment]
This is not so easy as I thought. It is possible to use libxml, take a look at those links:

http://xml4r.github.io/libxml-ruby/rdoc/index.html

http://eustaquiorangel.com/posts/validando_xml_com_ruby

**Comment by chaws** [comment]
If the goal is to check the XML integrity itself, I mean just to make sure all tags are being closed, all names are correct etc, I'd say just using a XML builder (libxml-ruby) would do it. Currently Kuniri has its own XML builder implementation.

Now if the purpose is validating XML tags names, tag order, parameter value types etc, then I'd go for the XSD specification (which is a pain to maintain). That's kinda useful.

**Comment by rodrigosiqueira** [comment]
Hello Chaws, :)
Actually, kuniri needs both of these approaches. First, we need to be sure about the basic output (the basic rules, for example). Secondly, we need to make our output more consistent and standardized, hence XSD is the best idea.
Can you help us with this?
