### ISSUE TITLE
A lot of methods with regex, reduce it.

### ISSUE THREAD

**Issue by rodrigosiqueira** [Kuniri/kuniri#157]
Reduce the excessive calling to get_{something} (for instance, get_class or get_attribute) in the state machine, because the ostensible use of regex.

If you take a careful look at files in lib/kuniri/state_machine/OO_structured_fsm, you will notice that get_{something} is called everytime by the same class or by other classes in the same directory. This a problem, because these kind of funtion has a lot of regex inside and the excessive calling to these functions can reduce the performance.

Pay attention to the different codes below, that shows an example of this problem:

``` ruby
require_relative 'oo_structured_state'
module StateMachine
  module OOStructuredFSM
    # Class responsible for handling Idle state.
    class IdleState < OOStructuredState
       ...
      # @see OOStructuredState
      def handle_line(pLine)
        if @language.externRequirementHandler.get_requirement(pLine)
          include_capture
        elsif @language.variableHandler.get_variable(pLine)
          variable_capture
        elsif @language.functionHandler.get_function(pLine)
          function_capture
        elsif @language.moduleHandler.get_module(pLine)
          module_capture
        elsif @language.classHandler.get_class(pLine)
          class_capture
        elsif ((@language.commentHandler.is_single_line_comment?(pLine)) || 
                (@language.commentHandler.is_multiple_line_comment?(pLine)))
          comment_capture
        else
          return
        end
      end
      ...
      # @see OOStructuredState
      def class_capture
        @language.set_state(@language.classState)
      end
      ...
    end
  end
end
```

and 

lib/kuniri/state_machine/OO_structured_fsm/class_state.rb

``` ruby
require_relative 'oo_structured_state'

module StateMachine
  module OOStructuredFSM
    # Class responsible for handling class state.
    class ClassState < OOStructuredState
      ...
      # @see OOStructuredState
      def handle_line(pLine)
        if @language.aggregationHandler.get_aggregation(pLine)
          aggregation_capture
        elsif @language.attributeHandler.get_attribute(pLine)
          attribute_capture
        elsif @language.constructorHandler.get_constructor(pLine)
          constructor_capture
        elsif @language.methodHandler.get_function(pLine)
          method_capture
        elsif @language.moduleHandler.get_module(pLine)
          module_capture
        elsif @language.aggregationHandler.get_aggregation(pLine)
          aggregation_capture
        elsif @language.commentHandler.is_single_line_comment?(pLine) ||
              @language.commentHandler.is_multiple_line_comment?(pLine)
          comment_capture
        end
      end
      ...
      # @see OOStructuredState
      def execute(pElementFile, pLine)
        classElement = @language.classHandler.get_class(pLine)
        ...
      end
    # End class
    end

  # End OOStructuredFSM
  end

# End module
end
```

Idea for solution:

Maybe we can use two approaches (together or not):
1. Use class attribute accessible by other classes in the same module.
2. Create some kind of Singleton, to keep a unique instances of state machine and the processed data. This approach, is a little bit hard because we have to think carefully before start to change.

**Comment by pwener** [comment]
Do you mean `"get_#{@functionIdentifier}"` should be replaced by 'real' methods?

**Comment by rodrigosiqueira** [comment]
I have to say sorry because of the poor description in this issue. I already updated it, and if you have any question, please ask again :)

**Comment by pwener** [comment]
Ok @rodrigosiqueira, now i understood, thank you by full description! I will work on it.

**Comment by pwener** [comment]
@rodrigosiqueira why this get_{something} are not statical methods?
1. They not depends of any instance
2. More cleaner and fast invocation: VariableGlobalRuby.find(pLine)
