### ISSUE TITLE
Executing kuniri on empty folder shows ruby error message

### ISSUE THREAD

**Issue by rodrigosiqueira** [Kuniri/kuniri#172]
How to reproduce the error:

```
mkdir emptyTest
kuniri emptyTest/ -o emptyParsed/ -l ruby

A bunch of ruby error
```

Suggestion (#171):
Quietly finish if not have any file that Kuniri can handle. It have to handle it in the Kuniri source code and in the command line.

**Comment by bsesso** [comment]
Fixed on #201
