### ISSUE TITLE
kuniri not handling multiple line extern requirement.

### ISSUE THREAD

**Issue by rodrigosiqueira** [Kuniri/kuniri#32]
Unfortunately, kuniri are not ready for handling multiple line requirement.

**Comment by simiaosimis** [comment]
This is already mapped in include_state.rb, look method handle_line.

**Comment by rodrigosiqueira** [comment]
I just realized this is not a problem, because ruby syntax not accept require or require_relative in a multiple line without any parameter. For example, this is not a valid line:

```ruby
require
    'faker'
```
However, kuniri still have two problems related to requires:
1 - It is not recognizing 'load'.
2 - It does not capture multiple line with "+", for example:
```ruby
require 'lalala/' +
   'xpto'
```
I believe the problem with "+" it is much more generic and not directed related to this issue, because of this I will consider just the first problem and create a new issue for the second problem (#169).
