### ISSUE TITLE
Attribute capture bug

### ISSUE THREAD

**Issue by rodrigosiqueira** [Kuniri/kuniri#5]
The attribute capture is not working correctly, the regex and the handling are really poor.

**Comment by GustJc** [comment]
Might have fixed with commit 69fa62119e0d5c79767dcdaff629d6bdb6c3a80e.
Just changed to '\w' instead of 'dot' and removed the terminator '$'
It worked fine in the examples I tried but might need to evaluate furthur.

Closing it for now.
