### ISSUE TITLE
Test problem

### ISSUE THREAD

**Issue by rodrigosiqueira** [Kuniri/kuniri#55]
**Target**: Test break sometimes.
**Problem**: Sometimes, when you run all test some of them fail. Then, if you run all tests again no one will break. Maybe this problem is related with ".kuniri" file.

**Comment by simiaosimis** [comment]
Here some pictures that evidence this bug

![kuniri_fail_test](https://cloud.githubusercontent.com/assets/2761487/9482982/ae6afcec-4b70-11e5-9b08-655d0d374e60.png)
![kuniri_fail_test2](https://cloud.githubusercontent.com/assets/2761487/9482983/ae6ebb02-4b70-11e5-9cd2-05be19123119.png)

**Comment by rodrigosiqueira** [comment]
Merged.
