### ISSUE TITLE
Update README to indicate ruby version

### ISSUE THREAD

**Issue by rodrigosiqueira** [Kuniri/kuniri#81]
It is not clear for everybody which version of ruby it is required for running kuniri. Make it clear on Readme.
Additionally, I suggest the discussion for make Kuniri works with ruby 1.9.

**Comment by simiaosimis** [comment]
apparently up and running on ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]

**Comment by rodrigosiqueira** [comment]
Merged.
