### ISSUE TITLE
Handling one line method/function/constructor

### ISSUE THREAD

**Issue by rodrigosiqueira** [Kuniri/kuniri#94]
**Problem:** Kuniri can't handle single line method/function/constructor declaration, and some specific inline syntax.
**Description:** See the code below:

`def xpto a + b end`
`def xpto a + b end;`
`def xpto a + b end; def abc a + b end; def lalala a + b end;`

Those code have a valid syntax on ruby, and Kuniri does not handling it. 

**Suggestion:** I recommend to add extra manipulation in "lib/kuniri/language/ruby/function_behavior_ruby.rb"

**Comment by JohnnysRibeiro** [comment]
kuniri does handle single line single methods when there are parameters are between brackets
for example
def xpto () a+b end
def xpto (a,b) a+b end

**Comment by rodrigosiqueira** [comment]
Thanks for your message Johnnys! I didn't know about this.
Kuniri still have some problems for handling parameter, based on your comment and in some bugs that I know, I created the issue below:

 Handling parameters #95
